version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: weekly
      day: saturday
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "@bringg/foundation"
    assignees:
      - yosiat
      - shamil
      - ramhr